[package]
name = "hugepage"
version = "0.1.0"
edition = "2021"
authors = ["Zhang Junyu <junyu92@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"